obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.70, 0.65], [0.70, -0.65], [-0.70, -0.65], [-0.75, 0.65]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_hokuyo_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}

